### ISSUE TITLE
Github Actions policies

### ISSUE THREAD

**Issue by ekr-cfa** [CDCgov/template#100]
Can you advise on the policy for the use of Github actions on CDCgov (not CDCent) repos.

1. Are there any restrictions on which external actions I can use in my own actions?
2. If there are restrictions, is the use of the r-lib actions (https://github.com/r-lib/actions) permitted?

**Comment by boris-ning-usds** [comment]
For Github actions on cdcgov...
1. There are no restrictions and developers should use their best judgement in reviewing the action's code and whether they could be following into a pit of [pad-left](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code).
2. r-lib actions can be used, try it out.
