### ISSUE TITLE
Adding members

### ISSUE THREAD

**Issue by kgostic** [CDCgov/template#104]
I'm a team lead at CFA and I'm looking for some help adding our analysts to CDC Gov.

* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)

Could you please add:

Juliet Pulliam, [slp0@cdc.gov](mailto:slp0@cdc.gov), jrcpulliam 

Beau Bruce, [lue7@cdc.gov](mailto:lue7@cdc.gov), bbbruce  

Andy Magee, [rzg0@cdc.gov](mailto:rzg0@cdc.gov), afmagee42 

George Vega Yon, [xrd4@cdc.gov](mailto:xrd4@cdc.gov), gvegayoncdc 

Ben Toh, [tjk3@cdc.gov](mailto:tjk3@cdc.gov), kokbent 

Guido Espana, [ukd0@cdc.gov](mailto:ukd0@cdc.gov), confunguido

Ryan Raasch, [xng3@cdc.gov](mailto:xng3@cdc.gov), ryanraaschCDC

**Comment by erik1066** [comment]
Hello @kgostic, I sent invites to all of these accounts except for George Vega Yon. His CDC email address is already active in `CDCgov` and so he should already be a member.
