### ISSUE TITLE
Add Juan (Antonio) Hernandez (antoniohndz1)  as member/collaborator to cfa_azure repo

### ISSUE THREAD

**Issue by ryanraaschCDC** [CDCgov/template#107]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

Please give access to Juan (Antonio) Hernandez with github username antoniohndz1 access to the cfa_azure repo. He has been helping develop this package from the CDCEnt side but he does not have the appropriate permissions to collaborate (push/pull/merge) with CDCgov/cfa_azure.
Thank you!

**Comment by erik1066** [comment]
I sent a GitHub invite to his CDC email address to join https://github.com/cdcgov. A repo admin can add him to any `CDCgov` repo once he accepts. I assume this is what was requested, as I believe you can otherwise invite him as an outside collaborator as a repo admin. Let me know.

**Comment by boris-ning-usds** [comment]
Checking the [cfa_azure](https://github.com/cdcent/cfa_azure/settings/access) repository. It looks like Antonio has write access to the repository which will allow him to push/pull/merge.

Closing ticket as completed.
![image](https://github.com/CDCgov/template/assets/41026275/2822a840-c201-41f4-9d00-efbcf8e81dd7)
