### ISSUE TITLE
CDCgov add user request

### ISSUE THREAD

**Issue by alismx** [CDCgov/template#110]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

Requesting that we add Shanice to the CDCgov organization for the SimpleReport project.

Name: Shanice Musiitwa
GitHub handle:  @shanice-skylight
Email: xod8@cdc.gov

Please let me know if you need any other information!

VR,
Alis

**Comment by boris-ning-usds** [comment]
I've invited Shanice - [xod8@cdc.gov](mailto:xod8@cdc.gov) earlier today and communicated it over Teams.

Closing ticket as completed.
