### ISSUE TITLE
New Repo: data-exchange-event-sync

### ISSUE THREAD

**Issue by cosmycx** [CDCgov/template#115]
**Is your feature request related to a problem? Please describe.**
New code repository for an utility data exchange service.

**Describe the solution you'd like**
A new code repository.

**Describe alternatives you've considered**
Mono repo with other tools.

**Additional context**
CDC OCIO Data Exchange Project.

**Comment by boris-ning-usds** [comment]
@cosmycx - created a public repository called data-exchange-event-sync and made you the admin.
https://github.com/CDCgov/data-exchange-event-sync
