### ISSUE TITLE
New Repository Request: `reportstream-sftp-ingestion`

### ISSUE THREAD

**Issue by halprin** [CDCgov/template#117]
**What type of help do you need?**

* [ ] Question
* [x] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please create a new public repository in this organization called `reportstream-sftp-ingestion`.  This will be a separate service to support ReportStream receiving files via SFTP.  Please add me, @halprin, as an admin.

**Comment by boris-ning-usds** [comment]
Repository created for Peter Kendall (ujg1), admin rights added.
