### ISSUE TITLE
Add user to CDCgov Github Org

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/template#121]
Hello, please add cvaish963 - Vaishali Cholkar. She will be working as a devops engineer on the PRIME project. Her email is vaishali.cholkar@icf.com, her CDC account is in process.

**Comment by boris-ning-usds** [comment]
Invited [vaishali.cholkar@icf.com](mailto:vaishali.cholkar@icf.com) to cdcgov. Please let them know to accept the request.
