### ISSUE TITLE
Invite `jherrflexion` to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/template#123]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

Please invite @jherrflexion to the CDCgov GitHub organization. Their CDC e-mail is [XTP3@cdc.gov](mailto:XTP3@cdc.gov).

**Comment by boris-ning-usds** [comment]
Sent an invite to [XTP3@cdc.gov](mailto:XTP3@cdc.gov).
