### ISSUE TITLE
Invite `sdjpark` to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by halprin** [CDCgov/template#125]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please invite @sdjpark to the CDCgov GitHub organization.  Their CDC e-mail is hcp4@cdc.gov.

**Comment by boris-ning-usds** [comment]
Completed. I sent the request over to their CDC email, can they verify and pick it up from there - Peter?

**Comment by halprin** [comment]
> Completed. I sent the request over to their CDC email, can they verify and pick it up from there - Peter?

They accepted the invite as the new GitHub user `hcp4`.  Thanks!
