### ISSUE TITLE
Archive the data-exchange-portal repo

### ISSUE THREAD

**Issue by candace-campbell** [CDCgov/template#126]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [x] Other

**Please describe how you'd like us to help.**

I would like to archive the following repository: https://github.com/CDCgov/data-exchange-portal

**Comment by boris-ning-usds** [comment]
With Erik Knudsen (erik1066)'s blessing, I've archived data-exchange-portal.
