### ISSUE TITLE
Please delete this repo

### ISSUE THREAD

**Issue by kgostic** [CDCgov/template#128]
**Background**

My team produces CDC's Rt estimates. I think someone on my team created this repo a while ago, but we never initiated devleopment in it. I also don't have write or admin access and can't see who does. We're going to request creation of a repo with a different name now that we're picking this project back up, and I think it will be easiest to delete this one that we're no longer using.

**Comment by boris-ning-usds** [comment]
Got it; which repository did you want to delete?

**Comment by boris-ning-usds** [comment]
Talked to Katie - deleting https://github.com/CDCgov/COVID19-Rt - which was a blank template repository.
Closing ticket.
