### ISSUE TITLE
Requesting membership

### ISSUE THREAD

**Issue by mrajeev08** [CDCgov/template#129]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Could I add Michelle Fearon-Scales (cdc id: utg5, github user: mlfearon) to the CDCgov organization for eventual creation of repositories for public code sharing. She is familiar with CDC open practices.

**Comment by boris-ning-usds** [comment]
I sent an invite to their email, they will need to accept the invitation within 7 days to get access to https://github.com/cdcgov.
