### ISSUE TITLE
Add existing repositories to SonarCloud

### ISSUE THREAD

**Issue by szamfir** [CDCgov/template#130]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ X] Other

**Please describe how you'd like us to help.**

-Please add the following 2 repositories to the SonarCloud: 
1. https://github.com/CDCgov/NEDSS-NNDSS
2. https://github.com/CDCgov/NEDSS-DataReporting

-For the 2 new projects created within Sonarcloud please grant user szamfir@github the following permissions: Administer Issues, Administer Security Hotspots, Administer, Execute Analysis.

**Comment by boris-ning-usds** [comment]
Created SonarCloud scans and added your privileges via [terraform](https://github.com/cdcent/ocio-sonarcloud-infra/pull/4)
- https://sonarcloud.io/project/roles?id=CDCgov_NEDSS-DataReporting
- https://sonarcloud.io/project/roles?id=CDCgov_NEDSS-NNDSS

Feel free to check your roles there.
