### ISSUE TITLE
Request to be added to GH CDCgov flu-informatics team

### ISSUE THREAD

**Issue by rchau88** [CDCgov/template#131]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

I would like to request to be part of GH CDCgov flu-informatics team. Thanks so much!

**Comment by boris-ning-usds** [comment]
@sammysheep - Sam, as the maintainer of flu-informatics team, can we add snu3 - rchau88 onto the flu-informatics team?

**Comment by leebrian** [comment]
I'm a maintainer too and you can add her. Reina really just needs to be a CDCGov member so we can add her.

**Comment by boris-ning-usds** [comment]
Completed and Reina should have access now.

**Comment by rchau88** [comment]
Thank you again Brian and Ning!
