### ISSUE TITLE
Remove `rajeev-flexion` from CDCgov

### ISSUE THREAD

**Issue by halprin** [CDCgov/template#132]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please remove the `rajeev-flexion` user from the CDCgov GitHub organization.

**Comment by boris-ning-usds** [comment]
Completed. Removed [rajeev-flexion](https://github.com/rajeev-flexion) from CDCgov org.
