### ISSUE TITLE
Invite `pluckyswan` to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by halprin** [CDCgov/template#133]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please invite @pluckyswan to the CDCgov GitHub organization.  Their CDC e-mail is zmh7@cdc.gov.

**Comment by erik1066** [comment]
Invite sent to the specified CDC email address.
