### ISSUE TITLE
Invite `xop5` to CDCGov

### ISSUE THREAD

**Issue by ryanraaschCDC** [CDCgov/template#134]
**What type of help do you need?**

* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)

Please invite `xop5` (Fawad Rafi) with email address xop5@cdc.gov to CDCGov. He will be assisting in the development of cfa_azure.

**Comment by boris-ning-usds** [comment]
Sent an invite to [xop5@cdc.gov](mailto:xop5@cdc.gov). They'll have 7 days to accept the invitation.
