### ISSUE TITLE
Please add the following users to the CDCgov org

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/template#138]
This will be the team taking over managing PRIME ReportStream starting Sept 30th.

Scott Zimmerman - scott-aquia - scott.zimmerman@aquia.io
Eduardo Valdes - emvaldes eduardo.valdes@aquia.io
Chris Jones - magikid - scott.zimmerman@aquia.io
Matt Szubrycht - devopsmatt - matt.szubrycht@aquia.io

If you have questions after the 30th please contact Patrick Stoneburner jaa0@cdc.gov

**Comment by boris-ning-usds** [comment]
Are these folks in the process of being onboarded to CDC (with network access)?

**Comment by jeremy-page** [comment]
Yes, they have submitted their eQIP stuff already and should go pretty fast since they are coming from a different Federal contract.

**Comment by boris-ning-usds** [comment]
Completed.
