### ISSUE TITLE
Add cfa-admin and cfa-predict teams to cfa_azure

### ISSUE THREAD

**Issue by ryanraaschCDC** [CDCgov/template#139]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [x] Other

Per Nimesh Patel's request, please add cfa-admin group with role `Admin` and cfa-predict group with role `Maintain` to the cfa_azure repository (https://github.com/CDCgov/cfa_azure). Thank you!

**Comment by boris-ning-usds** [comment]
Looks like this has been completed already before I got to it in https://github.com/CDCgov/cfa_azure/settings/access.

Closing as completed.
![image](https://github.com/user-attachments/assets/d6cd5d4e-1cd1-4b40-95a0-8cfe31a3c851)

**Comment by ryanraaschCDC** [comment]
perfect, thanks for letting me know!
