### ISSUE TITLE
Add the CDC Re-engineering team to CDCgov org

### ISSUE THREAD

**Issue by emmanuel-apau** [CDCgov/template#14]
* [x] User Membership

- AJKimpo - Anthony Kimpo (OCIO)
- kenmitchell - Ken Mitchell  (OCIO)
- cfarmer-fearless - Chase Farmer (OCIO)
- dsueltenfuss - David Sueltenfuss (OCIO)
- pbsanghvi1002 - Prakash Sanghvi (OCIO)
- ChrisB-16 - Chris Bajulaiye (OCIO)
- anandCD405 - Anand Erram (OCIO)
- rohitpanwar - Rohit Panwar (OCIO)

Product Owner: @boris-ning-usds

**Comment by leebrian** [comment]
Would you please add these folks names and orgs to this issue to help with keeping track of who's who? Theoretically, they'll all update their profiles with names and whatnot after they join the org.

**Comment by boris-ning-usds** [comment]
I'm not sure if my approval is needed here - Brian has the final say to this. I approve (if needed).

I can also add the context.
This team will be working as part of the GSA Fearless / Center of Excellence (COE) team to support Enterprise Data Exchange (EDE/DEX) on infrastructure needs. Additionally, they'll be building out various tech enablers for aligning our cloud environment needs.
