### ISSUE TITLE
Please remove user from CDCorg

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/template#141]
Please remove the following user from the CDCgov org:
Chris - magikid

**Comment by boris-ning-usds** [comment]
> Please remove the following user from the CDCgov org: Chris - magikid

The user [magikid](https://github.com/magikid) doesn't have access to any cdcgov or cdcent repositories.

**Comment by jeremy-page** [comment]
Ok, he was in the ticket from yesterday so I wanted to make sure. He's not going to be working for the CDC.

**Comment by boris-ning-usds** [comment]
Got it. Marking ticket as completed.
