### ISSUE TITLE
Gain access to Codecov for the RecordLinker repo

### ISSUE THREAD

**Issue by derekadombek** [CDCgov/template#142]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [x] Other

**Please describe how you'd like us to help.**
Hello there! I was told to request for a Codecov access token here. Our repo is https://github.com/CDCgov/RecordLinker. We would like to add this to our unit testing github action. Please let me know what needs to be done for this. Thank you!

**Comment by boris-ning-usds** [comment]
I approved the Github App earlier, but wasn't sure what Codecov access token includes.
Are there any instructions on how to get that, or do you have everything you need?

**Comment by derekadombek** [comment]
Thank you for the approval! I submitted that shortly after creating this issue think that might work and it seemed to work for my personal account but I `believe` Codecov in the CDC org needs to be configured by the account owner? I'm def new to configuring this but when I try from with the repo settings I get this: 
![Screenshot 2024-10-01 at 1 31 52 PM](https://github.com/user-attachments/assets/368a8b6a-528e-49ab-9f20-eb7a970846ba)

Also I was reading this doc earlier and shows theres an access token needed to use with github actions https://docs.codecov.com/docs/quick-start

**Comment by boris-ning-usds** [comment]
Have you tried logging into codecov via https://app.codecov.io/login, via your Github sign on, and see if you can generate a token?

Because I don't think I've generate any tokens for anybody for this app, and I suspect they're able to do it just fine.
Also, if it's a little more involved, can you setup 15-20 mins with me (tpz7@cdc.gov) and we can just screenshare and get it completed?

**Comment by derekadombek** [comment]
That definitely seems correct that I should be able to generate a token on my end from the Codecov UI the more I look into this. I think the issue is, Currently I can only configure my personal repos but not the RecordLinker repo because I'm an admin and not the repo owner. I agree on meeting up! That might help clarify some things. I will send you an invite thanks again!

**Comment by boris-ning-usds** [comment]
Ah, got it. You're an outside collaborator to https://github.com/cdcgov/RecordLinker.
I just sent you an invitation to be a full member on cdcgov. That might fix the problem.

**Comment by derekadombek** [comment]
That seemed like a good try! unfortunately when I go into the repo settings to configure the app i still get the banner that I need to be a organization owner :( 
![Screenshot 2024-10-04 at 8 35 31 AM](https://github.com/user-attachments/assets/15081d3b-8f78-4485-8965-46dd3c4ae128)
![Screenshot 2024-10-04 at 8 34 24 AM](https://github.com/user-attachments/assets/e0cf1a1c-4608-4f8a-bac2-12cee503818d)

**Comment by boris-ning-usds** [comment]
I think we're meeting some time this upcoming week on this - so let's solve this then.

**Comment by boris-ning-usds** [comment]
We updated the member list to include Derek on codecov (but no luck on access, may need a followup). I gave Derek a codecov secret to add to RecordLinker to connect them as a remediation step.

**Comment by boris-ning-usds** [comment]
Closing ticket as completed.
