### ISSUE TITLE
moving existing cdcent repo to cdcgov

### ISSUE THREAD

**Issue by arik-shurygin** [CDCgov/template#144]
**What type of help do you need?**
We have been developing on CDCent and want to move our entire repository, history and issues included, to CDCgov.  The existing repo on CDCent is https://github.com/cdcent/cfa-scenarios-model
 
**Please describe how you'd like us to help.**
As this requires elevated permissions, we would appreciate assistance in moving our repository from CDCent to CDCgov.  If this isn't the right place to make this request, please let us know.

Cross posted this issue here as well: [Moving existing CDCent repo to CDCgov · Issue #356 · cdcent/enterprise_practices (github.com)](https://github.com/cdcent/enterprise_practices/issues/356)

**Comment by boris-ning-usds** [comment]
Completed the migration - it's been moved to https://github.com/CDCgov/cfa-scenarios-model/settings/access
