### ISSUE TITLE
Invite `amcnuttJMC` to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by halprin** [CDCgov/template#145]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please invite @amcnuttJMC to the CDCgov GitHub organization.  Their CDC e-mail is AL64@cdc.gov.

**Comment by boris-ning-usds** [comment]
Request received by Peter Kendall - sent out an invite to [amcnuttJMC](https://github.com/amcnuttJMC). They'll have 7 days to accept the invitation.

If they can, they should also associate their email (doesn't have to be primary) to their Github handle:
https://github.com/settings/emails
