### ISSUE TITLE
Invite JScott-JMC to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/template#148]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please invite @JScott-JMC to the CDCgov GitHub organization. Their CDC e-mail is [awo5@cdc.gov](mailto:awo5@cdc.gov).

**Comment by boris-ning-usds** [comment]
Invitation sent to [JScott-JMC](https://github.com/JScott-JMC). They will have to accept the invitation within 7 days.
