### ISSUE TITLE
Please add new team members

### ISSUE THREAD

**Issue by kgostic** [CDCgov/template#149]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

I'm a data science lead at CFA and I'm wondering if you could please add these team members to CDC Gov?

Name / CDID / github id
Patrick Corbett, pyv3@cdc.gov, PatrickTCorbett
Kingsley Iyawe, rlv7@cdc.gov, kingsleyiyawe

**Comment by boris-ning-usds** [comment]
Invited [kingsleyiyawe](https://github.com/kingsleyiyawe) and [PatrickTCorbett](https://github.com/PatrickTCorbett) to https://github.com/cdcgov, they'll have 7 days to accept the invitation.
