### ISSUE TITLE
Add Two CDC COE Team Members to this Org

### ISSUE THREAD

**Issue by cfarmer-fearless** [CDCgov/template#15]
Team member access.

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership
* [ ] Other

Can you please add the following CDC COE team members to the CDCgov GitHub org?
 - ChrisB-16 - Chris Bajulaiye (OCIO)
 - rohitpanwar - Rohit Panwar (OCIO)

**Comment by leebrian** [comment]
I invited Chris and Rohit.
