### ISSUE TITLE
Invite dbgolson to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/template#150]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please invite @dbgolson to the CDCgov GitHub organization. Their CDC e-mail is [xou3@cdc.gov](mailto:ZSB9@cdc.gov).

**Comment by boris-ning-usds** [comment]
Inviting [dbgolson](https://github.com/dbgolson) to https://github.com/cdcgov. They'll have 7 days to accept the invitation.
