### ISSUE TITLE
Sam Wiley @dzw2 CDCGov github join

### ISSUE THREAD

**Issue by samcwiley** [CDCgov/template#151]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
Hello I would like to be added to the CDCGov organization so that I can contribute to Flu Bioinformatics repositories and have my contributions be visible when the projects become open sourced. Samuel Shepard @vfn4 is my supervisor and recommended that I join the organization. Thank you.

**Comment by boris-ning-usds** [comment]
Verified user via Teams; sent out an invitation. Sam will have 7 days to accept the invitation.
