### ISSUE TITLE
Request approval for fine grained PAT

### ISSUE THREAD

**Issue by sbidari** [CDCgov/template#153]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [x] Other

**Please describe how you'd like us to help.**
We are adding functionality to approve, and merge pull requests from verified collaborators on the [CovidHub repo](https://github.com/CDCgov/covid19-forecast-hub). I am currently stress testing this feature on the [covidhub-sandbox](https://github.com/CDCgov/covidhub-sandbox/tree/main) repo and would like to request approval for the fine grained Personal Access Token to use in Github Actions workflow.

cc'd @dylanhmorris for visibility

**Comment by boris-ning-usds** [comment]
It's been approved. I approved it about an hour ago.

**Comment by dylanhmorris** [comment]
Thank you!
