### ISSUE TITLE
I need permissions to setup Github workflows

### ISSUE THREAD

**Issue by xop5** [CDCgov/template#154]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

I need to set up automated tests through Github workflow in https://github.com/CDCgov/cfa_azure 
Currently I only have permission to commit code in this repository. However I don't have permissions to run workflow or look at the workflow logs.

**Comment by boris-ning-usds** [comment]
Pinging Nimesh Patel (cva2) on the type of access and team you should be on since I usually don't touch the CFA repositories as there are dedicated teams added to the repositories.

**Comment by boris-ning-usds** [comment]
I've added you as admin to the repository; https://github.com/CDCgov/cfa_azure/settings/access?guidance_task= by Nimesh's permission.

**Comment by boris-ning-usds** [comment]
Closing ticket as completed.
