### ISSUE TITLE
Give Arik Shurygin as maintainer on cfa_azure

### ISSUE THREAD

**Issue by ryanraaschCDC** [CDCgov/template#157]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
Please give Arik Shurygin (username arik-shurygin) maintainer access to the cfa_azure repo so that he can push branches and merge PRs. Thank you!

**Comment by boris-ning-usds** [comment]
Mapping arik-shurygin to uva5.

**Comment by boris-ning-usds** [comment]
Completed.
