### ISSUE TITLE
Invite JeremyIR to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/template#158]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please invite @JeremyIR to the CDCgov GitHub organization. Their CDC e-mail is [ap13@cdc.gov](mailto:ap13@cdc.gov).

**Comment by boris-ning-usds** [comment]
Invitation sent to [JeremyIR](https://github.com/JeremyIR) after verification. They should accept the invitation within 7 days.
