### ISSUE TITLE
Invite odeleongt to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by odeleongt** [CDCgov/template#159]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
Please invite @odeleongt to the CDCgov GitHub organization. My CDC e-mail is [yfn1@cdc.gov](mailto:yfn1@cdc.gov).

**Comment by boris-ning-usds** [comment]
Invited this user to cdcgov after verifying identity.
