### ISSUE TITLE
Add CDC COE Scrum Master Kelsey Melefsky to the CDCgov Github Org

### ISSUE THREAD

**Issue by cfarmer-fearless** [CDCgov/template#16]
The CDC COE team needs their scrum master added to the CDCgov GitHub org in order for her to have access to the Zenhub scrum board.

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership
* [ ] Other

Please add user kmelefsky to this org.

**Comment by leebrian** [comment]
I just invited Kelsey to CDCGov. Please work with her to set up her profile per the [open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) so it's easy for folks to know their name, org, etc.
