### ISSUE TITLE
New CodeCov Token for CDCGov/phdi

### ISSUE THREAD

**Issue by JNygaard-Skylight** [CDCgov/template#160]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [x] Other

 I was told I could request a Codecov access token here. Our repo is https://github.com/CDCgov/phdi. We already have a `CODECOV_TOKEN` secret but it must no longer be valid. I get `error - 2024-12-10 19:55:52,761 -- Upload failed: {"message":"Repository not found"}` when I try to reimplement Codecov in our Github actions.

**Comment by boris-ning-usds** [comment]
Hmm, I thought I passed over a token before, and when logging into codecov, I see the following:
![image](https://github.com/user-attachments/assets/fd7f119d-70c1-47e2-941e-7e445a687dce)

I'll send a one-time link with the token to your CDC email.

**Comment by JNygaard-Skylight** [comment]
That fixed it, thank you!

**Comment by boris-ning-usds** [comment]
Oh, just to add a note, I don't think there's a time expiration on that token (at least I don't see anywhere where it says it expires). This might be a one-time event from Codecov.
