### ISSUE TITLE
Add CDC PRIME SimpleReport team member Arin Kulshi to this org

### ISSUE THREAD

**Issue by emyl3** [CDCgov/template#161]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please add new team member Arin Kulshi to this org. Github username is `arinkulshi-skylight` - https://github.com/arinkulshi-skylight
Please let me know if you need any more information from us to add Arin. Thank you so much!

**Comment by boris-ning-usds** [comment]
They have been added as of yesterday and I'm seeing activity of their user. Closing ticket as completed.
