### ISSUE TITLE
Sign up for Github Actions Beta

### ISSUE THREAD

**Issue by emmanuel-apau** [CDCgov/template#18]
**What type of help do you need?**

Can one of the GitHub org admins sign up for the GitHub actions beta. We want to take advantage of being able to set static IP's for our CI runners so we can lock down access to our cloud services better.

Sign URL: https://github.com/features/github-hosted-runners/signup

Context:
https://github.blog/2022-09-01-github-actions-introducing-the-new-larger-github-hosted-runners-beta/

* [x] Other

**Comment by leebrian** [comment]
Sadly, CDCGov is not managed in an enterprise so not eligible for the beta. We can turn it on for CDCEnt and CDCAI, but that  won't help your CDCGov repos.

**Comment by emmanuel-apau** [comment]
@leebrian hey that's fine, we only need it for CDCEnt actually

**Comment by leebrian** [comment]
Great, I signed up for the beta and got this message "You’ve agreed to the [pre-release terms](https://docs.github.com/site-policy/github-terms/github-terms-for-additional-products-and-features#previews) with the account cdc. We’ll notify you once you’ve gained access, make sure your primary email address is up to date. If you have any questions, let us know via our [community feedback discussions](https://github.com/community/community/discussions/categories/actions-and-packages)."

I'll keep this item in waiting and update it when we get accepted so you'll know it's available.

I don't see how these runners affect our actions minutes so hopefully it's something reasonable.

**Comment by emmanuel-apau** [comment]
Perfect thanks!

**Comment by leebrian** [comment]
That was pretty fast, just got an email with "Your account is onboarded to the new beta for larger GitHub-hosted runners and fixed IPs!"

From my end it looks like it's setup and ready with some larger ubuntu runners. And someone already ran a job.

Let me know over on cdcent how it's going and if you need anything else set up.
