### ISSUE TITLE
Add users from CFA

### ISSUE THREAD

**Issue by kgostic** [CDCgov/template#19]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

I am a data scientist in CFA's predict division, and I'd like to add myself and several members of my team to CDCgov:

* Katelyn Gostic (cdc: uep6@cdc.gov, github: kgostic)
* Scott Olesen (ulp7@cdc.gov, swo)
* Nishant Kishore (ynm2@cdc.gov, nish-kishore)
* Danielle Richard (qrd9@cdc.gov, dmrichard)
* Jason Asher (swo9@cdc.gov, jasonasher)

A bit about CFA and our goals: We are a new center focused on outbreak modeling and data analytics. We would like to start a few public repos for organizational purposes (a style guide in bookdown; a repo of utility scripts for common models, analyses, and inference procedures, etc.), and as we staff up we're interested in developing modeling tools using open practices in CDCgov.

**Comment by erik1066** [comment]
Invites sent for those five users to `CDCgov`.
