### ISSUE TITLE
Add user for NBS

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/template#20]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

I would like to have Serban Zamfir added to CDCGov.  Serban works for Enquizit and is part of the team working on NBS modernization.  He will be responsible for our SonarCloud configuration and in order to do that will need to be a member of CDCGov (Sonar syncs the github org member list).

Please invite:

| Name | CDC handle | Github handle |
| - | - | - |
| Serban Zamfir | uba0 | @szamfir |

Thank you!

**Comment by erik1066** [comment]
Invite sent
