### ISSUE TITLE
Add Chromatic to prime-reportstream

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/template#23]
**Is your feature request related to a problem? Please describe.**
As the development of the ReportStream website ramps up, it's become more difficult to collaborate with our designers on visual treatments and behaviors.  To that end, we're going to be spinning up a local [Storybook](https://storybook.js.org/) instance, and we'd like to use [Chromatic](https://www.chromatic.com/) as a hosting solution so non-engineers can peruse our styleguide and components as needed.

**Describe the solution you'd like**
Add [the Chromatic app](https://www.chromatic.com/docs/access) to the CDCgov/prime-reportstream repository.  Permissions are based on GitHub permissions so maintenance thereafter should be handled automatically.

**Describe alternatives you've considered**
An alternate solution would be to build and deploy on our own resources, but our team doesn't have the bandwidth to take that on now.  Chromatic would help to give us It may be considered in the future if needed.

**Additional context**
N/A

**Comment by erik1066** [comment]
Hi Stephen,

I just set configured it for `CDCgov/prime-reportstream`. I believe that's all that's needed on my end. Let me know if there's something else I need to do. Good luck and happy coding!

**Comment by stephenkao** [comment]
Hi, @erik1066.  Thank you so much for the speedy response!

One more thing, and then I think we should be good to go: would you mind sending me the Chromatic project token for us to use in CI jobs?  It can be found when logging in at chromatic.com and selecting the prime-reportstream project:

<img width="1087" alt="Screenshot 2023-03-15 at 10 47 49" src="https://user-images.githubusercontent.com/2421042/225346692-e415a4c1-7515-413c-818b-ad76a01c89f3.png">

If you have Keybase, I'm available at stephenkaonava.  Otherwise, you can email it to me at umk5@cdc.gov or stephenkao@navapbc.com -- or I'm happy to make myself available wherever you'd prefer.  Thanks in advance!

**Comment by stephenkao** [comment]
Hi, @erik1066.  Just checking in on getting the project token from Chromatic so we can start integrating our project with the public side of things.  Let me know if you need any more details about how we intend to use it, but we're basically just going to be following [this doc](https://www.chromatic.com/docs/setup) to set up it for us.  

Thank you!

**Comment by erik1066** [comment]
Hi Stephen,

Token sent.

**Comment by stephenkao** [comment]
Hi, Erik.  Sorry to belabor this issue, but where did you send the token?  I'm not seeing it in Keybase or in either of my email inboxes.  Thanks again!
