### ISSUE TITLE
PRIME ReportStream team members to add to CDCgov

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/template#24]
Please add the following users to the CDCgov org

Name | GitHub Username | Date Requested | Date Added | CDC User
Joseph Andersen | @jpandersen87 | 4/4/23 |   | ujr1@cdc.gov
Brandon Canniff | @brandonnava | 4/4/23 |   | ujw8@cdc.gov
Jimmy Fagan | @jimmyfagan | 4/4/23 |   | ujx4@cdc.gov
Chris Kuryak | @chris-kuryak | 4/4/23 |   | ule6@cdc.gov
Victor Chaparro | @victor-chaparro | 4/4/23 |   | ulh5@cdc.gov
Lizzie Mannie | @lizzieamanning | 4/4/23 |   | ume1@cdc.gov
Avniel Dravid | @avnieldravid | 4/4/23 |   | ume5@cdc.gov
Stephen Kao | @stephenkao | 4/4/23 |   | umk5@cdc.gov
Jillian Hammer | @jillian-hammer | 4/4/23 |   | umn1@cdc.gov
Arnej Duranović | @arnejduranovic | 4/4/23 |   | umn2@cdc.gov
Jessica Willis | @JessicaWNava | 4/4/23 |   | unw2@cdc.gov
Angela DeGolier | @adegolier | 4/4/23 |   | uoq2@cdc.gov
Audrey Ross | @audreykwr | 4/4/23 |   | usu6@cdc.gov

**Comment by erik1066** [comment]
Hi Jeremy, invites sent to those email addresses.

**Comment by jeremy-page** [comment]
This is complete, thank you!
