### ISSUE TITLE
Add new team members

### ISSUE THREAD

**Issue by kgostic** [CDCgov/template#25]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
Could you please add the following analysts to CDCGov? These are all new data scientists in CFA. (We are growing fast!)

John Humphreys, unp7, JMHumphreys
Catherine Herzog, uvw5, cherz4
Inga Holmdahl, usn4, iholmdahl
Eric Mooring, pgv5, eqmooring
Michael Batista, upi8, mrbatist
Danielle Richard, qrd9, dmrichard
Trevor Martin, upx3, Fg6K7h4fhy2

Once they are in the CDCGov organization, I can add them to our cfa-predict team and give them write access to https://github.com/CDCgov.

**Comment by kgostic** [comment]
Edit to the last line above: I can give them write access to https://github.com/CDCgov/covid19-forecast-hub

**Comment by erik1066** [comment]
Done.
