### ISSUE TITLE
Add new CFA Analyst to CDCGov Github

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/template#26]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

I am a new data scientist in CDC/OD/CFA. Could you please add me to the CDCGov GitHub Organization? 

 

Name: Kaitlyn Johnson

Cdcid: uox1

GitHub: kaitejohnson

**Comment by erik1066** [comment]
Done! Happy coding
