### ISSUE TITLE
Onboard members of Enterprise Data Exchange (EDE/DEX)

### ISSUE THREAD

**Issue by boris-ning-usds** [CDCgov/template#27]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
I would like to onboard new members to Enterprise Data Exchange (EDE/DEX). A similar request will be made to cdcent for the following personnels.

1. Abbey Salvo
Github name: fearless-abbey
Org Info: OCIO/DSO
Project: Enterprise Data Exchange 
Role: Senior Designer

2. Linda Zhou
Github name: dancing-goats
Org Info: OCIO/DSO
Project: Enterprise Data Exchange 
Role: Software Engineer

3. Terevid Ahlakor
Github name: tahlakor
Org Info: OCIO/DSO
Project: Enterprise Data Exchange 
Role: Technical Writer

**Comment by erik1066** [comment]
Invited all 3 per their CDC email addresses.

**Comment by boris-ning-usds** [comment]
Closing, we should be good to go here.
