### ISSUE TITLE
New User Membership

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/template#30]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

I am a new data scientist in CDC/OD/CFA. Could you please add me to the CDCGov GitHub Organization? 
Name: Zachary Susswein 
Cdcid: utb2
GitHub: @zsusswein

**Comment by boris-ning-usds** [comment]
Completed.

**Comment by zsusswein** [comment]
Thanks!
