### ISSUE TITLE
Add new CFA analyst to CDCGov Github

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/template#31]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
I am a new data scientist in CDC/OD/CFA. Could you please add me to the CDCGov GitHub Organization? 
Name: Nathan McIntosh
Cdcid: ute2 
GitHub: @natemcintosh

**Comment by boris-ning-usds** [comment]
Completed.
