### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by jbenter29** [CDCgov/template#34]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
CDC DAX Jira migration

**Comment by boris-ning-usds** [comment]
Hi Jacques,
I'm not familiar with the DAX Jira migration. Which team are you working with?

**Comment by jbenter29** [comment]
I'm with Fearless, we are working on a project to migrate Zenhub to a Jira
Cloud and as part of it there are connections to GitHbu for DAX
program.  Leslyn can provide more details as I am not versed in all the
team names myself.

*Jacques **Benter *
*IT** Manager*

email ***@***.***
main 410.394.9600 <410-394-9600>
office 8 Market Place #304, Baltimore
<https://maps.google.com/?q=8+Market+Place+%23304,+Baltimore&entry=gmail&source=g>

*fearless.tech* <https://fearless.tech/>   |   What we do
<https://fearless.tech/work/services>   |   Join our team
<https://fearless.tech/careers>

**Comment by boris-ning-usds** [comment]
Ah, DEX = Data Exchange, not DAX.

Got it. Onboarding.

**Comment by jbenter29** [comment]
Ahh you are right. Thank you. Sent from my iPhoneOn May 16, 2023, at 6:04 PM, Boris Ning ***@***.***> wrote:﻿
Ah, DEX = Data Exchange, not DAX.
Got it. Onboarding.

**Comment by boris-ning-usds** [comment]
This is completed. I'm closing this issue.
