### ISSUE TITLE
Join github.com/cdcgov

### ISSUE THREAD

**Issue by emilio32-lang** [CDCgov/template#35]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [*] Other

I need to join https://github.com/cdcgov in order to get access to the HL7 DEX repos.
I am a new developer on the DEX team.
Thanks
Emil Hristov, eph0@cdc.gov

**Comment by boris-ning-usds** [comment]
Added you to cdcgov. You will want to contact Leslyn McNabb directly on write access to the DEX repos, and I would prefer it if your team members were also grouped under a Github team.
