### ISSUE TITLE
User Membership

### ISSUE THREAD

**Issue by loretta-work** [CDCgov/template#39]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

**Comment by erik1066** [comment]
Hello, I'll need a list of CDC users to add to the `CDCgov` organization - soon as I have that, I can handle this for you.

**Comment by loretta-work** [comment]
Just 1 - Loretta Foster kra6@cdc.gov aka loretta-work

**Comment by erik1066** [comment]
Invite sent to your CDC email address.
