### ISSUE TITLE
Please add me to CDC GOV git hub instance. I work with Data exchange (DEX)

### ISSUE THREAD

**Issue by manandappa** [CDCgov/template#41]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

**Comment by erik1066** [comment]
This was completed - closing. Let us know if we need to reopen.
