### ISSUE TITLE
Please add new CFA data scientist to CDC Gov

### ISSUE THREAD

**Issue by kgostic** [CDCgov/template#42]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Could you please add Casey Middleton, a new data scientist at CFA to CDC Gov so that she can access our repos? Her CDC ID is utx4@cdc.gov and her github username is CaseyMiddleton.

**Comment by erik1066** [comment]
Invite sent to [utx4@cdc.gov](mailto:utx4@cdc.gov).
