### ISSUE TITLE
Add new CFA analyst to CDCGov Github

### ISSUE THREAD

**Issue by caseyzipfel** [CDCgov/template#45]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
I am a new data scientist in CDC/OD/CFA. Please add me to the CDCGov GitHub Organization.
Full name: Casey Zipfel
CDC ID: ruv5
GitHub ID: caseyzipfel

**Comment by erik1066** [comment]
Invite sent to your CDC email address.
