### ISSUE TITLE
Add new CFA analyst to CDCGov Github 

### ISSUE THREAD

**Issue by rncrgl** [CDCgov/template#48]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

I am a new ORISE fellow in CDC/OD/CFA. Please add me to the CDCGov GitHub Organization. My name is Ronan Corgel, my cdc ID is uub3 and my GitHub username is rncrgl. Thank you!

**Comment by erik1066** [comment]
Invite sent to your CDC email address.
