### ISSUE TITLE
Add ReportStream developers to GitHub org

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/template#51]
Please add the following outside collaborators (github usernames) as members of the CDCgov GitHub org so that I can add them to a GitHub team.

Example error:
![image](https://github.com/CDCgov/template/assets/5522990/bb2d2fc2-a4a8-4f04-9363-e2be1ca9813f)

- GilmoreA6
- brick-green
- adegolier
- penny-lischer
- jpandersen87
- jalbinson
- etanb
- jack-h-wang
- victor-chaparro
- arnejduranovic
- JessicaWNava
- mkalish
- thetaurean
- kant777
- cloudmagic80
- luis-pabon-tf
- jimmyfagan

**Comment by boris-ning-usds** [comment]
Done. Invite sent to everybody here except people who are already added previously.
