### ISSUE TITLE
New Employee Membership

### ISSUE THREAD

**Issue by rrubiaco** [CDCgov/template#52]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

**Comment by boris-ning-usds** [comment]
Welcome to CDC, Ryan.
