### ISSUE TITLE
Add new member to CDCGov Github 

### ISSUE THREAD

**Issue by ekr-cfa** [CDCgov/template#54]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
I am supporting CDC/OD/CFA. Please add me to the CDCGov GitHub Organization.

**Comment by boris-ning-usds** [comment]
Hi, could you ping me on Teams (tpz7) or provide me with your name so that I can log it down?

Thanks,
-Boris

**Comment by boris-ning-usds** [comment]
Completed.
