### ISSUE TITLE
Add new CFA analyst to CDCGov Github

### ISSUE THREAD

**Issue by ChiragKumar9** [CDCgov/template#57]
I am a new data scientist in CDC/OD/CFA. Please add me to the CDCGov GitHub Organization.

Name: Chirag Keshav Kumar
CDC ID: kzs9
GitHub ID: ChiragKumar9

Please let me know if I can provide any additional information. Thank you!

**Comment by boris-ning-usds** [comment]
Invitation sent, have fun!

-Boris
