### ISSUE TITLE
Add new CFA analyst to CDCGov Github

### ISSUE THREAD

**Issue by theresaSheets** [CDCgov/template#63]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
I am a new data scientist in CDC/OD/CFA. Please add me to the CDCGov GitHub Organization.

Name: Theresa Sheets
CDC ID: utg8
GitHub ID: theresaSheets

**Comment by boris-ning-usds** [comment]
Sent the invite, have fun! Will close this ticket once you have verified access to the organization.

**Comment by boris-ning-usds** [comment]
Closing issue - haven't gotten a response; I believe this has been resolved.
