### ISSUE TITLE
Add ReportStream developers to GitHub org

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/template#66]
Please add the following outside collaborators (github usernames) as members of the CDCgov GitHub org so that I can add them to a GitHub team.

- [supriyaaddagada](https://github.com/supriyaaddagada)

**Comment by john-qeh3** [comment]
Please add the following collaborator as members of the CDCgov GitHub org so that I can add them to a GitHub team.

[john-qeh3](https://github.com/john-qeh3)

**Comment by boris-ning-usds** [comment]
Added [supriyaaddagada](https://github.com/supriyaaddagada) and [john-qeh3](https://github.com/john-qeh3) as members of cdcgov.

FYI, the term "outside collaborators" are usually only used as collaborators to a single Github repository, and in this case, they'll be full members to cdcgov, so I assume you meant members or full members instead.

**Comment by boris-ning-usds** [comment]
I can only send out an invitation, if they don't accept - there's not much I can do.

Sending out another invitation. Can they check their email?
![image](https://github.com/CDCgov/template/assets/41026275/3c5a6617-85e9-43f5-8223-2617f88ff600)
