### ISSUE TITLE
User membership request

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/template#69]
Please add brianserotini to the CDCgov org, he will be assisting us with some scrum related tasks.

Thank you

**Comment by boris-ning-usds** [comment]
Hey @jeremy-page, can you provide the full name of the user and a contact email, preferably their cdc.gov email?
We're changing some policies because it makes it difficult to know when to offboard users.

**Comment by jeremy-page** [comment]
Name: Brian Serotini
Org:  Not sure, he is an ICF employee like me, he is only interested in PRIME at the CDC
Email: vzj0@cdc.gov
gitlab handel: brianserotini

**Comment by erik1066** [comment]
Invite sent to that user's CDC email address. They will have 7 days from now to accept or the invite will expire.
