### ISSUE TITLE
Add new CFA contractor to CDCGov Github

### ISSUE THREAD

**Issue by k88hudson-cfa** [CDCgov/template#73]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
I am a new contractor working with CDC/OD/CFA. Please add me to the CDCGov GitHub Organization.

My details are as follows:
Katherine Hudson
ryl8@cdc.gov
k88hudson-cfa

**Comment by erik1066** [comment]
Your CDC email account should have invite to github.com/CDCgov. Happy coding!
