### ISSUE TITLE
Invite `jcrichlake` to CDCgov GitHub Organization

### ISSUE THREAD

**Issue by halprin** [CDCgov/template#76]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please invite @jcrichlake to the CDCgov GitHub organization.  Their CDC e-mail is stq2@cdc.gov.

**Comment by erik1066** [comment]
Invite sent to the user's CDC email address.

**Comment by halprin** [comment]
This worked.  Thanks!
