### ISSUE TITLE
Request Membership to CDCgov GH Instance

### ISSUE THREAD

**Issue by qoh4** [CDCgov/template#77]
I am requesting access to membership within the CDCgov GH Instance per direction from others. Let me know if I need to provide any further information for this to proceed.

**Comment by erik1066** [comment]
Hello qoh4, can you provide one of the GitHub administrators a CDC email address we can send the invite link to?

**Comment by qoh4** [comment]
Should be that ***@***.******@***.***>. Does that not suffice? Thanks for the help.

JACOB THOMAS | Contractor

Peraton | Data Engineer

C: (678) 779-6746 | ***@***.******@***.***>
