### ISSUE TITLE
Please grant access to the security scanning settings of the prime-reportstream repo

### ISSUE THREAD

**Issue by dkrylovsb** [CDCgov/template#79]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [x] Other

I need to work on [this ticket](https://github.com/CDCgov/prime-reportstream/issues/9651), but appear to not have enough permissions on that repo. Could you please grant `dkrylovsb` access to the security scanning settings of the `prime-reportstream` repo so that I could finish that ticket? Thanks!

**Comment by boris-ning-usds** [comment]
@dkrylovsb
I read [the ticket](https://github.com/CDCgov/prime-reportstream/issues/9651), can you check with Jeremy on your access needs for that repository, since he has the power to grant it too.
