### ISSUE TITLE
User Membership for NBS project members

### ISSUE THREAD

**Issue by szamfir** [CDCgov/template#81]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please add the following individuals as members.
umw3@cdc.gov, uij8@cdc.gov, upt9@cdc.gov, upy4@cdc.gov, usq9@cdc.gov

**Comment by erik1066** [comment]
@szamfir, I just sent the invites to those 5 individuals. The invites expire in 7 days. Since it's the Wednesday before a federal holiday and many people will be out on leave, please let me know if those staff were unable to accept in time and I can re-send them.
