### ISSUE TITLE
Add Elizabeth Misas to CDCgov for collaboration on mycosnp-nf

### ISSUE THREAD

**Issue by mrajeev08** [CDCgov/template#86]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
Could you please add https://github.com/AspTryGlu from the Mycotic Diseases Branch to CDCgov for collaboration on mycosnp-nf?

**Comment by erik1066** [comment]
An invite has been sent to that user's CDC email address. The user should accept the GitHub CDCgov invite within 7 days. Once they accept, the repository administrator of mycosnp-nf can add [AspTryGlu](https://github.com/AspTryGlu) as a member of the repo.

**Comment by mrajeev08** [comment]
@erik1066, could we reopen this as Elizabeth (nye9@cdc.gov) was not able to accept the invite on time. Thank you!

**Comment by erik1066** [comment]
@mrajeev08 : Invite re-sent just now.
