### ISSUE TITLE
User onboard for Olufemi Orelaja onto cdcgov. 

### ISSUE THREAD

**Issue by Oorelaja** [CDCgov/template#88]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**
User onboard for Olufemi Orelaja onto cdcgov. CDC username is tsd0 . Github handle is oorelaja

**Comment by boris-ning-usds** [comment]
Hi Olufemi - I sent an invite but it'll expire within 7 days, so please be sure to accept the invitation.

**Comment by boris-ning-usds** [comment]
User has been onboarded, closing ticket.
