### ISSUE TITLE
URL to the R&D lab's code of conduct is broken in the code-of-conduct document

### ISSUE THREAD

**Issue by erik1066** [CDCgov/template#9]
**Describe the bug**
In the code of conduct file underneath the [Credit](https://github.com/CDCgov/template/blob/master/code-of-conduct.md#credit) section, the URL to the R&D lab's code of conduct is broken.  The broken URL is http://www.phiresearchlab.org/?page_id=1715.

Navigating to the URL causes a browser timeout.

**Impact**
We're unable to read a potentially useful code of conduct

**To Reproduce**
1. Navigate to https://github.com/CDCgov/template/blob/master/code-of-conduct.md#credit
2. Click on the URL titled "CDC's Informatics Innovation Unit R&D Lab's code of conduct"
3. Observe a browser timeout

**Expected behavior**
The R&D Lab's code of conduct displayed in a browser.

**Screenshots**
Not applicable

**Logs**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 74

**Comment by leebrian** [comment]
Thanks for the issue, fixed to point to proper link.
