### ISSUE TITLE
New Member Onboarding

### ISSUE THREAD

**Issue by sublettk** [CDCgov/template#91]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please add `xqz2` (CDC ID) to the cdcgov org.

**Comment by erik1066** [comment]
I sent an invite to that user just now. They have 7 days to accept the invite before it expires.
