### ISSUE TITLE
CDCgov add user request

### ISSUE THREAD

**Issue by alismx** [CDCgov/template#92]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

Requesting that we add Mike to the CDCgov organization for the SimpleReport project.

Name: Mike Brown
GitHub handle:  @mpbrown
Email: ggs2@cdc.gov

Please let me know if you need any other information!

VR,
Alis

**Comment by boris-ning-usds** [comment]
Invitation sent to ggs2.

**Comment by alismx** [comment]
Thank you, the team member has accepted the invite so it looks like we're all set!
