### ISSUE TITLE
New Member Request

### ISSUE THREAD

**Issue by sublettk** [CDCgov/template#93]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Please add `xqz6` (CDC ID) to the cdcgov org.

**Comment by boris-ning-usds** [comment]
Invite sent to xqz6@cdc.gov
